### PR TITLE
updates to support latest sonarqube version and added test cases

### PR DESCRIPTION
**Pull request by geofflancaster**
Removes deprecated api calls and supports sonarqube 7.9. closes https://github.com/usaa/sonar-quality-gates/issues/5

### CODE REVIEW

**Comment by geofflancaster** [comment]
@josephndenton this is ready for review. Thanks!

**Comment by josephndenton** [comment]
Can you update the CHANGELOG and squash commits?

**Comment by geofflancaster** [comment]
@josephndenton CHANGELOG has been updated and commits have been squashed.

**Comment by geofflancaster** [comment]
@josephndenton bump

**Review by josephndenton — APPROVED** [review]
LGTM

**Pull request merged**
